steps:
  - label: ':node: spectre-ui verify'
    key: 'verify'
    command:
      - 'npm ci'
      - 'npm run ci:verify'
    agents:
      queue: 'default'
    artifact_paths:
      - 'dist/**/*'
    timeout_in_minutes: 20
