export interface UtilityDefinition {
  className: string;
  declarations: string[];
}

export const LAYOUT_UTILITIES: UtilityDefinition[] = [
  { className: 'block', declarations: ['display: block;'] },
  { className: 'inline-block', declarations: ['display: inline-block;'] },
  { className: 'inline', declarations: ['display: inline;'] },
  { className: 'flex', declarations: ['display: flex;'] },
  { className: 'inline-flex', declarations: ['display: inline-flex;'] },
  {
    className: 'grid',
    declarations: [
      'display: grid;',
      'grid-template-columns: repeat(1, minmax(0, 1fr));',
    ],
  },
  { className: 'hidden', declarations: ['display: none;'] },
  { className: 'flex-row', declarations: ['flex-direction: row;'] },
  { className: 'flex-row-reverse', declarations: ['flex-direction: row-reverse;'] },
  { className: 'flex-col', declarations: ['flex-direction: column;'] },
  { className: 'flex-col-reverse', declarations: ['flex-direction: column-reverse;'] },
  { className: 'flex-wrap', declarations: ['flex-wrap: wrap;'] },
  { className: 'flex-wrap-reverse', declarations: ['flex-wrap: wrap-reverse;'] },
  { className: 'flex-nowrap', declarations: ['flex-wrap: nowrap;'] },
  { className: 'flex-1', declarations: ['flex: 1 1 0%;'] },
  { className: 'flex-auto', declarations: ['flex: 1 1 auto;'] },
  { className: 'flex-initial', declarations: ['flex: 0 1 auto;'] },
  { className: 'flex-none', declarations: ['flex: none;'] },
  { className: 'grow', declarations: ['flex-grow: 1;'] },
  { className: 'grow-0', declarations: ['flex-grow: 0;'] },
  { className: 'shrink', declarations: ['flex-shrink: 1;'] },
  { className: 'shrink-0', declarations: ['flex-shrink: 0;'] },
  { className: 'justify-start', declarations: ['justify-content: flex-start;'] },
  { className: 'justify-end', declarations: ['justify-content: flex-end;'] },
  { className: 'justify-center', declarations: ['justify-content: center;'] },
  { className: 'justify-between', declarations: ['justify-content: space-between;'] },
  { className: 'justify-around', declarations: ['justify-content: space-around;'] },
  { className: 'justify-evenly', declarations: ['justify-content: space-evenly;'] },
  { className: 'items-start', declarations: ['align-items: flex-start;'] },
  { className: 'items-end', declarations: ['align-items: flex-end;'] },
  { className: 'items-center', declarations: ['align-items: center;'] },
  { className: 'items-baseline', declarations: ['align-items: baseline;'] },
  { className: 'items-stretch', declarations: ['align-items: stretch;'] },
  { className: 'content-start', declarations: ['align-content: flex-start;'] },
  { className: 'content-end', declarations: ['align-content: flex-end;'] },
  { className: 'content-center', declarations: ['align-content: center;'] },
  { className: 'content-between', declarations: ['align-content: space-between;'] },
  { className: 'content-around', declarations: ['align-content: space-around;'] },
  { className: 'content-evenly', declarations: ['align-content: space-evenly;'] },
  { className: 'content-stretch', declarations: ['align-content: stretch;'] },
  { className: 'self-auto', declarations: ['align-self: auto;'] },
  { className: 'self-start', declarations: ['align-self: flex-start;'] },
  { className: 'self-end', declarations: ['align-self: flex-end;'] },
  { className: 'self-center', declarations: ['align-self: center;'] },
  { className: 'self-stretch', declarations: ['align-self: stretch;'] },
  { className: 'self-baseline', declarations: ['align-self: baseline;'] },
  { className: 'static', declarations: ['position: static;'] },
  { className: 'fixed', declarations: ['position: fixed;'] },
  { className: 'absolute', declarations: ['position: absolute;'] },
  { className: 'relative', declarations: ['position: relative;'] },
  { className: 'sticky', declarations: ['position: sticky;'] },
  { className: 'inset-0', declarations: ['inset: var(--sp-space-0);'] },
  {
    className: 'inset-x-0',
    declarations: ['left: var(--sp-space-0);', 'right: var(--sp-space-0);'],
  },
  {
    className: 'inset-y-0',
    declarations: ['top: var(--sp-space-0);', 'bottom: var(--sp-space-0);'],
  },
  { className: 'top-0', declarations: ['top: var(--sp-space-0);'] },
  { className: 'right-0', declarations: ['right: var(--sp-space-0);'] },
  { className: 'bottom-0', declarations: ['bottom: var(--sp-space-0);'] },
  { className: 'left-0', declarations: ['left: var(--sp-space-0);'] },
  { className: 'w-auto', declarations: ['width: auto;'] },
  { className: 'w-full', declarations: ['width: 100%;'] },
  { className: 'w-fit', declarations: ['width: fit-content;'] },
  { className: 'min-w-0', declarations: ['min-width: 0;'] },
  { className: 'min-w-full', declarations: ['min-width: 100%;'] },
  { className: 'max-w-none', declarations: ['max-width: none;'] },
  { className: 'max-w-full', declarations: ['max-width: 100%;'] },
  { className: 'h-auto', declarations: ['height: auto;'] },
  { className: 'h-full', declarations: ['height: 100%;'] },
  { className: 'h-fit', declarations: ['height: fit-content;'] },
  { className: 'min-h-0', declarations: ['min-height: 0;'] },
  { className: 'min-h-full', declarations: ['min-height: 100%;'] },
  { className: 'max-h-none', declarations: ['max-height: none;'] },
  { className: 'max-h-full', declarations: ['max-height: 100%;'] },
  { className: 'overflow-auto', declarations: ['overflow: auto;'] },
  { className: 'overflow-hidden', declarations: ['overflow: hidden;'] },
  { className: 'overflow-clip', declarations: ['overflow: clip;'] },
  { className: 'overflow-visible', declarations: ['overflow: visible;'] },
  { className: 'overflow-scroll', declarations: ['overflow: scroll;'] },
  { className: 'overflow-x-auto', declarations: ['overflow-x: auto;'] },
  { className: 'overflow-x-hidden', declarations: ['overflow-x: hidden;'] },
  { className: 'overflow-x-scroll', declarations: ['overflow-x: scroll;'] },
  { className: 'overflow-y-auto', declarations: ['overflow-y: auto;'] },
  { className: 'overflow-y-hidden', declarations: ['overflow-y: hidden;'] },
  { className: 'overflow-y-scroll', declarations: ['overflow-y: scroll;'] },
  { className: 'whitespace-normal', declarations: ['white-space: normal;'] },
  { className: 'whitespace-nowrap', declarations: ['white-space: nowrap;'] },
  { className: 'text-left', declarations: ['text-align: left;'] },
  { className: 'text-center', declarations: ['text-align: center;'] },
  { className: 'text-right', declarations: ['text-align: right;'] },
  { className: 'object-contain', declarations: ['object-fit: contain;'] },
  { className: 'object-cover', declarations: ['object-fit: cover;'] },
  { className: 'object-fill', declarations: ['object-fit: fill;'] },
  { className: 'object-none', declarations: ['object-fit: none;'] },
  { className: 'object-scale-down', declarations: ['object-fit: scale-down;'] },
  { className: 'object-top', declarations: ['object-position: top;'] },
  { className: 'object-right', declarations: ['object-position: right;'] },
  { className: 'object-bottom', declarations: ['object-position: bottom;'] },
  { className: 'object-left', declarations: ['object-position: left;'] },
  { className: 'object-center', declarations: ['object-position: center;'] },
  { className: 'aspect-auto', declarations: ['aspect-ratio: auto;'] },
  {
    className: 'border',
    declarations: [
      'border-width: var(--sp-component-border-width);',
      'border-style: solid;',
      'border-color: var(--sp-surface-divider);',
    ],
  },
  {
    className: 'border-t',
    declarations: [
      'border-top-width: var(--sp-component-border-width);',
      'border-top-style: solid;',
      'border-top-color: var(--sp-surface-divider);',
    ],
  },
  {
    className: 'border-r',
    declarations: [
      'border-right-width: var(--sp-component-border-width);',
      'border-right-style: solid;',
      'border-right-color: var(--sp-surface-divider);',
    ],
  },
  {
    className: 'border-b',
    declarations: [
      'border-bottom-width: var(--sp-component-border-width);',
      'border-bottom-style: solid;',
      'border-bottom-color: var(--sp-surface-divider);',
    ],
  },
  {
    className: 'border-l',
    declarations: [
      'border-left-width: var(--sp-component-border-width);',
      'border-left-style: solid;',
      'border-left-color: var(--sp-surface-divider);',
    ],
  },
  { className: 'border-none', declarations: ['border: none;'] },
  { className: 'list-none', declarations: ['list-style: none;'] },
  { className: 'list-disc', declarations: ['list-style: disc;'] },
  { className: 'list-decimal', declarations: ['list-style: decimal;'] },
  { className: 'list-inside', declarations: ['list-style-position: inside;'] },
  { className: 'list-outside', declarations: ['list-style-position: outside;'] },
];

export const AUTO_MARGIN_UTILITIES: UtilityDefinition[] = [
  { className: 'm-auto', declarations: ['margin: auto;'] },
  { className: 'mx-auto', declarations: ['margin-left: auto;', 'margin-right: auto;'] },
  { className: 'my-auto', declarations: ['margin-top: auto;', 'margin-bottom: auto;'] },
  { className: 'mt-auto', declarations: ['margin-top: auto;'] },
  { className: 'mr-auto', declarations: ['margin-right: auto;'] },
  { className: 'mb-auto', declarations: ['margin-bottom: auto;'] },
  { className: 'ml-auto', declarations: ['margin-left: auto;'] },
];
