import { fileURLToPath } from "node:url";
import { join } from "node:path";
import tailwindcss from "@tailwindcss/vite";
import type { AstroIntegration } from "astro";

export interface TailwindOptions {
  /** CSS module to import automatically. Set to `false` to opt out. */
  entry?: string | false;
}

export interface SpectreUIOptions {
  /** Prefix for the autogenerated import alias (default: `spectre-ui`). */
  alias?: string;
  /** Configure Tailwind CSS v4 support. Pass `false` to disable. */
  tailwind?: boolean | TailwindOptions;
}

const packageDir = fileURLToPath(new URL(".", import.meta.url));
const componentsDir = join(packageDir, "components");
const stylesDir = join(packageDir, "styles");

export default function spectreUI(options: SpectreUIOptions = {}): AstroIntegration {
  const alias = options.alias ?? "spectre-ui";
  const tailwindOption = options.tailwind ?? true;

  return {
    name: "spectre-ui",
    hooks: {
      "astro:config:setup"({ config, updateConfig, injectScript }) {
        const aliasEntries = {
          [alias]: packageDir,
          [`${alias}/components`]: componentsDir,
          [`${alias}/styles`]: stylesDir,
        };

        const existingAlias = config.vite?.resolve?.alias;
        const mergedAlias = Array.isArray(existingAlias)
          ? [
              ...existingAlias,
              ...Object.entries(aliasEntries).map(([find, replacement]) => ({ find, replacement })),
            ]
          : {
              ...(typeof existingAlias === "object" && existingAlias !== null ? existingAlias : {}),
              ...aliasEntries,
            };

        const rawPlugins = config.vite?.plugins;
        const plugins = Array.isArray(rawPlugins)
          ? rawPlugins.slice()
          : rawPlugins
            ? [rawPlugins]
            : [];

        if (tailwindOption !== false) {
          plugins.push(tailwindcss());

          const entry =
            typeof tailwindOption === "object" && "entry" in tailwindOption
              ? (tailwindOption.entry ?? `${alias}/styles/base.css`)
              : `${alias}/styles/base.css`;

          if (entry) {
            injectScript("page-ssr", `import '${entry}';`);
          }
        }

        updateConfig({
          vite: {
            resolve: {
              ...(config.vite?.resolve ?? {}),
              alias: mergedAlias,
            },
            plugins,
          },
        });
      },
    },
  };
}

export type { SpectreButtonProps } from "./components/button.types";
