import { fileURLToPath } from "node:url";
import { join } from "node:path";
import type { AstroIntegration } from "astro";

export interface SpectreUIOptions {
  /** Prefix for the autogenerated import alias (default: `spectre-ui`). */
  alias?: string;
}

const packageDir = fileURLToPath(new URL(".", import.meta.url));
const componentsDir = join(packageDir, "components");

export default function spectreUI(options: SpectreUIOptions = {}): AstroIntegration {
  const alias = options.alias ?? "spectre-ui";

  return {
    name: "spectre-ui",
    hooks: {
      "astro:config:setup"({ updateConfig }) {
        updateConfig({
          vite: {
            resolve: {
              alias: {
                [alias]: packageDir,
                [`${alias}/components`]: componentsDir,
              },
            },
          },
        });
      },
    },
  };
}

export type { SpectreButtonProps } from "./components/button.types";
